#!/bin/bash

# by Lewis Hellewell (22943954)
# Abstract max commands to reduce code repitition, however, abstract for other two would hurt readability and create too much conditional clutter

# Command line options
options="
	cyber_breaches <filename> <command>
		maxstate
			Returns the two letter code for the state that has the largest number of incidents across all years, and the corresponding count. 
			(If more than one, any one of them is returned).

		maxyear
			Returns the year with the greatest number of incidences across all the states, and the corresponding count. 
			(If more than one, any one of them is returned).

		A two letter state code (AZ)
			Returns the year with the maximum number of incidents, and the count. 
			(If more than one, any one of them is returned).

		A four digit year (YYYY)
			Returns the state with the maximum number of incidents for that year, and the count. 
			(If more than one, any one of them is returned).
			"

# Displays options
if [ $# -eq 0 ]; then
    echo "$options"
    exit 0

elif [[ ! -f "$1" ]] # File not found in directory
then
    echo "	File not found!"
    exit 1;
fi


# Get the file name
file=$1

# Get the command
cmd=$2;

# Abstract max commands to avoid repetition of code
# Grabs any command with max infront incase of incorrect value type input
if [[ $cmd == "max"* ]]; 
then
	if [[ $cmd == "maxstate"  || $cmd == "maxyear" ]]; 
	then
		# Initialises the two abstract variables
		columnNumber=0
		valueType=""
		if [[ $cmd == "maxstate" ]];
		then
			columnNumber=2	# Column number to cut from the data file
			valueType="State"
		else
			columnNumber=8	# Column number to cut from the data file
			valueType="Year"
		fi
		
		# Value with most occurances in file
		topValue=$(cut -f $columnNumber "$file" | sort | uniq -c | sort -rn | head -n 1)

		# Extract value and the occurences
		occurences=$(echo $topValue | cut -d ' ' -f1)
		value=$(echo $topValue | cut -d ' ' -f2)

		echo "$valueType with greatest number of incidents is: $value with count $occurences
		"

		exit 0;
	else
		echo "The max commands are either maxstate or maxyear
		"
		exit 1;
	fi
elif [[ $cmd =~ ^[A-Za-z]{2}$ ]];
then
	# Convert to upper case
	cmd=${cmd^^}

	# Extract the years where recorded breaches occurred (for iteration)
	years=$(cut -f8 -d"	" "$file" | tail -n +2 | sort | uniq)
	
	# Initialize the max variables
	maxCount=0
	maxYear=""

	# Iterate through each year
	for year in $years; do
		# Count the occurrences of the state for the current year
		count=$(cut -f2,8 -d"	" "$file" | tail -n +2| grep "^$cmd	$year" | wc -l)

		# Check count is larger than current maximum
		if [[ $count -gt $maxCount ]]; 
		then
        	maxCount=$count
        	maxYear=$year
    	fi
	done

	if [[ $maxCount -eq 0 ]];
	then
		echo "The state does not appear in the provided file with filename: $file.
		"
		exit 1
	else
		echo "Year with greatest number of incidents for $cmd is in $maxYear with count $maxCount
		"
		exit 0
	fi
elif [[ $cmd =~ ^[0-9]{4}$ ]];
then
	# Extract the states where recorded breaches occurred (for iteration)
	states=$(cut -f2 -d"	" "$file" | tail -n +2 | sort | uniq)

	# Initialise the max variables
	maxCount=0
	maxState=""

	# Iterate through each state
	for state in $states; do
		# Count the occurrences of the year in the current state
		count=$(cut -f2,8 -d"	" "$file" | tail -n +2| grep "^$state	$cmd" | wc -l)

		# Check count is larger than current maximum
		if [[ $count -gt $maxCount ]]; 
		then
        	maxCount=$count
        	maxState=$maxState
    	fi
	done

	if [[ $maxCount -eq 0 ]];
	then
		echo "The year does not appear in the provided file with filename: $file.
		"
		exit 1
	else
		echo "State with greatest number of incidents for $cmd is in $maxState with count $maxCount
		"
		exit 0
	fi
elif [[ $cmd =~ .{1,} ]];
then
	echo "	Invalid command argument, please execute without arguments and filename to view valid commands."
	exit 1
else
	echo "	Missing command argument, please execute without arguments and filename to view valid commands."
	exit 0
fi